backend:
  name: github
  repo: iiGreenFOXYT/iigreenfoxyt.github.io
  branch: main # Replace with your repository's default branch
  base_url: /admin # The path to access the CMS

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Date', widget: 'datetime' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
